# Introduction

NumPy = numerical computing with arrays
PyTorch = numerical computing + automatic differentiation + neural-network/ML tools

In [165]:
import torch

In [166]:
torch.__version__

'2.14.0+cpu'

In [167]:
def bCE(yHat, y):
    e = 1e-8
    yHat = yHat.clamp(e, (1-e))
    loss = -((y * (torch.log(yHat))) + ((1-y) * (torch.log(1-yHat))))
    return loss

In [168]:
x = torch.tensor([6.50, 1.0, 5.0, 6.7], dtype=torch.float32)
y = torch.tensor([1, 0, 1, 0], dtype=torch.float32)
type(x), y.shape, x.dtype 

(torch.Tensor, torch.Size([4]), torch.float32)

In [169]:
w = torch.ones((1), requires_grad=True, dtype=torch.float32)
b = torch.zeros((1), requires_grad=True, dtype=torch.float32)

In [170]:
z = w * x + b
z

tensor([6.5000, 1.0000, 5.0000, 6.7000], grad_fn=<AddBackward0>)

In [171]:
yHat = torch.sigmoid(z)
yHat

tensor([0.9985, 0.7311, 0.9933, 0.9988], grad_fn=<SigmoidBackward0>)

In [172]:
loss = bCE(yHat, y)
loss

tensor([1.5023e-03, 1.3133e+00, 6.7153e-03, 6.7012e+00],
       grad_fn=<NegBackward0>)

In [173]:
loss = loss.mean()
loss

tensor(2.0057, grad_fn=<MeanBackward0>)

In [174]:
loss.backward()

In [175]:
w.grad

tensor([1.8449])

In [176]:
b.grad

tensor([0.4304])

So as we can see, torch calculates derivative autometically and faster by using the AutoGrad method. Autograd can be thought of as a method/system for automatically computing derivatives, but in PyTorch it's more precise to call it an automatic differentiation engine. 

Autograd is PyTorch’s **automatic differentiation engine**; it automatically calculates derivatives (gradients) of tensors with respect to other tensors, so you don't have to derive them manually. It tracks the mathematical operations performed on tensors that have `requires_grad=True`, builds a **computation graph**, and when you call `loss.backward()`, it traverses that graph backward using the chain rule to calculate the gradients. So, **automatic differentiation is the general technique, while Autograd is PyTorch's implementation of that technique**.
